'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FrameSap2000.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;SLAB-data xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        '''	&lt;DECK&gt;
        '''		&lt;Name&gt;50/980&lt;/Name&gt;
        '''		&lt;Tickness&gt;0.7&lt;/Tickness&gt;
        '''		&lt;Weight&gt;7.01&lt;/Weight&gt;
        '''		&lt;Cost&gt;5.96&lt;/Cost&gt;
        '''	&lt;/DECK&gt;
        '''	&lt;DECK&gt;
        '''		&lt;Name&gt;50/980&lt;/Name&gt;
        '''		&lt;Tickness&gt;0.8&lt;/Tickness&gt;
        '''		&lt;Weight&gt;8.01&lt;/Weight&gt;
        '''		&lt;Cost&gt;6.82&lt;/Cost&gt;
        '''	&lt;/DECK&gt;
        '''	&lt;DECK&gt;
        '''		&lt;Name&gt;50/980&lt;/Name&gt;
        '''		&lt;Tickness&gt;0.9&lt;/Tickness&gt;
        '''		&lt;Weight&gt;9.01&lt;/Weight&gt;
        '''		&lt;Cost&gt;7.67&lt;/Cost&gt;
        '''	&lt;/DECK&gt;
        '''	&lt;DECK&gt;
        '''		&lt;Name&gt;50/980&lt;/Name&gt;
        '''		&lt;Tickn [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property Slab_data() As String
            Get
                Return ResourceManager.GetString("Slab_data", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
